### ISSUE TITLE
What build configuration is required to build a replacement OpenOCD executable?

### ISSUE THREAD

**Issue by gtaska** [cypresssemiconductorco/openocd#3]
**Have you looked for an answer?** Yes

**Question/Issue**:

I want to rebuild OpenOCD with a possible fix for issue #2. What options were/need to be provided to the ./configure script, so that I can build a drop-in replacement for versions that are released by this repo?

It would also be useful to have some kind of indication of the build environment that Cypress used to build their executable for Windows.

**Context**

See issue #2 

**Where did you expect to find the answer?**

I would expect there to be instructions in the README.md on how to set up the same build environment & configure options as what Cypress use to build the OpenOCD executable.

**Comment by rmbk19** [comment]
Hi @gtaska,

The procedure of building our fork of OpenOCD is the same as for the official mainline OpenOCD. It is described in the README file here http://openocd.org/doc-release/README

The only difference is that both, hidapi and libusb-1.0 development packages must be installed. Otherwise, the build will fail.
Please let us know if this works.

Thanks and Regards, 
Rakshith M B

**Comment by gtaska** [comment]
Sorry, I didn't state this in the original text - what build environment & configuration do you use when building a drop-in replacement executable for _Windows_?

OpenOCD has these notes (http://openocd.org/doc-release/README.Windows), offering two alternative environments.

**Comment by rmbk19** [comment]
Hi @gtaska,

We use MinGW-w64 for our official builds but it is also possible to build OpenOCD in Cygwin environment. But in the case of Cygwin, the resulting executable will probably have additional dependencies on Cygwin libraries. 
So it is recommended to use MinGW because the final executable will be standalone (it will not depend on any MinGW libraries etc).

Regards, 
Rakshith

**Comment by tbandtg** [comment]
Sorry to pile on here, but I am trying to build this to setup a GDBserver on a PSOC 6 connected to a RPI or SBC running on an arm chip. 
./configure --enable-cmsis-dap --enable-kitprog

Is this all I need? Or does it need more?

**Comment by rmbk19** [comment]
Hi @tbandtg, 

Can you please check this issue on a similar topic and let me know if it helps? - https://github.com/cypresssemiconductorco/openocd/issues/1

Regards, 
Rakshith
